name: Common SIT CI

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
  workflow_dispatch:
    inputs:
      tags:
        description: 'tags'
        required: true 

jobs:
  trigger_related_workflows:
    name: Trigger related workflows
    runs-on: ubuntu-latest
    if: github.event.base_ref=='refs/heads/main' || github.event_name == 'workflow_dispatch'
    
    steps:
      - name: Set env (Triggered by tagging)
        if: github.event.base_ref=='refs/heads/main'
        run: |
          echo "RELEASE_VERSION=${{ github.ref_name }}"
          echo "RELEASE_VERSION=${{ github.ref_name }}" >> $GITHUB_ENV

      - name: Set env (Triggered by workflow dispatch)
        if: github.event_name == 'workflow_dispatch'
        run: |
          echo "RELEASE_VERSION=${{ github.event.inputs.tags }}"
          echo "RELEASE_VERSION=${{ github.event.inputs.tags }}" >> $GITHUB_ENV

      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: ${{ env.RELEASE_VERSION }}
          fetch-depth: '2'

      - name: Observe changed files and trigger related SIT CI workflows
        run: |
          changedFilesString=$(git diff --name-only HEAD HEAD~1)
          changedFiles=(${changedFilesString// /})
          for changedFile in "${changedFiles[@]}";
            do
              case $changedFile in

                *"net48-app2/"*)
                  echo "TRIGGER_SIT_APP2=true" >> $GITHUB_ENV
                  ;;

              esac
            done

      - name: Trigger APP2 sit-ci.yml
        if: env.TRIGGER_SIT_APP2 == 'true'
        run: |
          echo "TRIGGER APP2 SIT-CI"